# Setup
title:        Elixir
tagline:      Main page of our project
baseurl:      "/Elixir/"
paginate:     1

# About/contact
author:
  name:       Abdulla Ouda
  url:        http://aouda6.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown